name: ALPPACA CI
# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  push:
    branches:
      - dev
  pull_request:
  release:
    types: [published]

env:
  NXF_ANSI_LOG: false

jobs:
  test:
    name: Run pipeline with test data
    # Only run on push if this is the nf-core dev branch (merged PRs)
    if: "${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'NorwegianVeterinaryInstitute/ALPPACA') }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Nextflow versions
        include:
          # Test pipeline minimum Nextflow version
          - NXF_VER: "23.04.4"
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool_cache: true

      - name: Check out pipeline code
        uses: actions/checkout@v4

      - name: Check out test data
        uses: actions/checkout@v4
        with:
          repository: NorwegianVeterinaryInstitute/ALPPACA
          ref: testdata
          path: testdata/

      - name: where are we
        run: pwd

      - name: check schema content
        run: ls -R assets/

      - name: Install Nextflow
        env:
          NXF_VER: ${{ matrix.NXF_VER }}
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: Run ani track test
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test_ani,docker --out_dir ./results

      - name: Run cgmlst track test
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test_cgmlst,docker --schema ${{ github.workspace }}/assets/data/test_schema/ --out_dir ./results

      - name: Run core genome track test
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test_core_genome,docker --out_dir ./results

      - name: Run core gene track test
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test_core_gene,docker --out_dir ./results

      - name: Run mapping track test
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test_mapping,docker --out_dir ./results
